apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.geoserver.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
{{- if not .Values.geoserver.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Values.geoserver.name }}
  template:
    metadata:
    {{- with .Values.geoserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ .Values.geoserver.name }}
    spec:
      containers:
        - name: overstroomik-geoserver
          image: "{{ .Values.images.geoserver.repository }}:{{ .Values.images.geoserver.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.geoserver.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /geoserver
              port: 8080
              scheme: HTTP
