# Config file for automatic testing at travis-ci.com
sudo: required

services:
  - docker

before_install:
  - mv .env.example .env
  - docker-compose up -d --build

script:
  - docker-compose exec backend bash scripts/test.sh

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" & "$TRAVIS_PULL_REQUEST_BRANCH" != ""]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker-compose push ;
    fi

after_script:
  - docker-compose down
