# Config file for automatic testing at travis-ci.com
sudo: required

services:
  - docker

before_install:
  - docker-compose up -d --build

script:
  - docker-compose exec backend bash scripts/test.sh

after_script:
  - docker-compose down
