version: "3.3"
services:

  geoserver:
    image: '${DOCKER_IMAGE_GEOSERVER?Variable not set}:${TAG-latest}'
    build:
      context: ./geoserver
    volumes:
      - ./geoserver/data_dir:/var/local/geoserver
    ports:
      - 8080:8080

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - geoserver
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    volumes:
      - ./backend:/app
    command: /start-reload.sh
    ports:
      - "8000:80"
