--2020-10-20 13:37:26--  https://app.swaggerhub.com/apiproxy/registry/overstroomik/overstroomik.nl/1.0.0?resolved=true&pretty=true
Resolving app.swaggerhub.com (app.swaggerhub.com)... 54.192.86.56, 54.192.86.49, 54.192.86.58, ...
Connecting to app.swaggerhub.com (app.swaggerhub.com)|54.192.86.56|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3682 (3,6K) [application/json]
Saving to: ‘1.0.0?resolved=true&pretty=true.3’

     0K ...                                                   100%  207M=0s

Last-modified header invalid -- time-stamp ignored.
2020-10-20 13:37:27 (207 MB/s) - ‘1.0.0?resolved=true&pretty=true.3’ saved [3682/3682]

