# Default values for overstroomik.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  geoserver:
    repository: deltares/overstroomik-geoserver
    tag: "latest"
  backend: deltares/overstroomik-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  imagePullSecrets: []

geoserver:
  name: "overstroomik-geoserver"
  podAnnotations: {}

  service:
    type: NodePort
    port: 8080

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 40
    # targetMemoryUtilizationPercentage: 80

  resources: {}

backend:
  name: "overstroomik-backend"
  podAnnotations: {}

  service:
    type: NodePort
    port: 80

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 40
    # targetMemoryUtilizationPercentage: 80

  resources: {}
  environment_variables:
    GEOSERVER_URL: http://overstroomik-geoserver:8080/geoserver
    https_proxy: null

ingress:
  environment: google
  enabled: true
  annotations:
    # gcloud compute addresses create overstroomik-static-ip --global
    # gcloud endpoints services deploy openapi.yaml
    kubernetes.io/ingress.global-static-ip-name: "overstroomik-static-ip"
  services:
    - name: overstroomik-geoserver
      path: /geoserver/*
      port: 8080
    - name: overstroomik-backend
      path: /*
      port: 80
