# Default values for overstroomik.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  geoserver:
    repository: deltares/overstroomik-geoserver
    tag: "0.1"
  backend: deltares/overstroomik-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  imagePullSecrets: []

geoserver:
  name: "overstroomik-geoserver"
  podAnnotations: {}

  service:
    type: ClusterIP
    port: 8080

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  resources: {}

  environment_variables:
    - key: JAVA_OPTS
      value: "-Xms8192m -Xmx8192m -Xss4m"

backend:
  name: "overstroomik-backend"
  podAnnotations: {}

  service:
    type: ClusterIP
    port: 80

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  resources: {}
  environment_variables:
    - key: https_proxy
      value: webproxy.rws.nl:8080
    - key: GEOSERVER_URL
      value: http://overstroomik-geoserver:8080/geoserver

ingress:
  environment: rws
  name: overstroomik
  host: overstroomik.k8s.shared.cnap.intranet.rws.nl
  enabled: true
  annotations: {}
  # gcloud compute addresses create overstroomik-static-ip --global
  # gcloud endpoints services deploy openapi.yaml
  # kubernetes.io/ingress.global-static-ip-name: "overstroomik-static-ip"
  services:
    - name: overstroomik-geoserver
      path: /geoserver/
      port: 8080
    - name: overstroomik-backend
      path: /
      port: 80
