name: Docker Compose Actions Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_BACKEND: deltares/overstroomik-service
      DOCKER_IMAGE_GEOSERVER: deltares/overstroomik-geoserver
      DOMAIN: localhost
      BACKEND_CORS_ORIGINS: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.asd.com", "https://stag.asd.com", "https://asd.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
      INSTALL_DEV: true
      COMPOSE: true
      FETCH_TIMEOUT: 60
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d --build
      - name: Test
        run: docker-compose exec backend bash scripts/test.sh
        
  release:
    if: ${{ github.ref == 'master' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the stack
        run: docker-compose build

      - name: Push the stack
        run: docker-compose push
