name: Docker Compose Actions Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: set environment variables
        run: mv .env.example .env
      - name: Build the stack
        run: docker-compose up -d --build
      - name: Test
        run: docker-compose exec -T backend bash scripts/test.sh
        
  release:
    if: ${{ github.ref == 'master' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the stack
        run: docker-compose build

      - name: Push the stack
        run: docker-compose push
